### ISSUE TITLE
[CORE] Improve build and tooling

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1624]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Satisfied Developers

### Actual behavior

There are little things that subtract from developer happiness. These things usually start out as minor, annoying things that one puts up with because they are focused on other things. However, the continually subtract from a pleasant developer experience and over time they add up to big frustrations and occasionally block development. 

This Issue is a bucket to collect and group issues. Additionally there may be proposed improvements that we might not have time to do when working on other issues. 

I'm starting with four categories. 

1. **Building** is related to the tooling used to build and publish the Clarity library. 
2. **Testing** is related to the tooling for writing and running the Clarity unit and css regression tests
3. **Dev/Debugging** is related to how we can develop new components and features as well as triage and debug issues that come up with the least amount of friction between the library code and its use in an application
4. **Support** is related to handling some of the areas around support requests that we get on various channels and platforms. 

## Building
- [ ] add chat bot to auto deploy clarity from the Slack #release channel
- [ ] investigate clang:format not removing \n after methods and at end of files
- [ ] Auto build the website on branch changes to the `new-website` branch
- [ ] Move large file assets (images for cssRegression and sketch files for design resources etc) into an external resource so they don't continue to contribute to the growing size of the repo
- [ ] Fix code coverage testing
- [ ] Look into a [webpack dashboard](https://github.com/FormidableLabs/webpack-dashboard)

## Testing
- [ ] Move css regression reference images out of the repo and into a solution that still makes it easy for external contributors to 1) run css regression tests on their forked pull request branch and 2) generate new reference images when needed 3) Preserve and protect the reference images for master branch
- [ ] Sourcemaps when running tests

## Dev/Debugging
- [ ] Remove the errors webpack throws when serving our sample/demo app
- [ ] Configure webpack to only print reports that include the latest changes / test results when running in watch mode
- [ ] Fix scss source maps for demo app
- [ ] Look into adding [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard)

## Support
- [ ] Integrate StackOverflow questions into one of our slack channels

**Comment by gnomeontherun** [comment]
This is stale, and no longer relevant in many ways. We can open new issues for specific improvements as needed.
