### ISSUE TITLE
Update design libraries

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1998]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Tasks
- [x] add updated Date Picker to UI Lib
- [x] add updated Date Picker to UI Lib - dark
- [x] add vol 10 icons from #1787
- [ ] update labels and downloads on the [Get Started](https://vmware.github.io/clarity/documentation/get-started) page

### Files
[Icon Lib](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-Icons-Library-0.11.6.sketch)
[UI Lib](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-0.11.6.sketch)
[UI Lib dark](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-dark-0.11.6.sketch)

### Environment details
* **Clarity version:** 0.11.5
* **Library version:** 0.11.0

**Comment by reddolan** [comment]
[Icon Lib](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-Icons-Library-0.11.6.sketch)
[UI Lib](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-0.11.6.sketch)
[UI Lib dark](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-dark-0.11.6.sketch)
