### ISSUE TITLE
Sketch Library updates

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#2069]
```
[X] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
- [x] updated UI Libraries (light, dark)
- [x] updated Icon Library
- [X] update version numbers on download buttons - on [Get Started page](https://vmware.github.io/clarity/documentation/v0.11/get-started)

### Updates
- [x] Add Button Dropdown
- [x] Add Button Dropdown DT
- [x] Button color changes #1939 
- [x] App-Level Alerts - resizing issues
- [x] App-Level Alerts - resizing issues DT
- [x] App-Level Alerts - add close icon
- [x] App-Level Alerts - add close icon DT
- [x] App-Level Alerts - add pagination version
- [x] App-Level Alerts - add pagination version DT
- [x] Vertical nav resizing issues #2098 
- [x] Vertical nav resizing issues #2098 DT
- [x] Resizing issue on Dropdown Divider override
- [x] Resizing issue on Dropdown Divider override DT
- [x] Add vol 11 icons to Icon Library #2101 
- [x] Update icon instances in Vertical Nav symbol to use symbols from Icon Library
- [x] Update icon instances in Vertical Nav symbol to use symbols from Icon Library DT
- [x] New Forms updates

**Comment by reddolan** [comment]
@adityarb88 the updates are complete. Here are links to the files:
[UI Library 0.12.1](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-0.12.1.sketch)
[UI Library - dark 0.12.1](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-dark-0.12.1.sketch)
[Icon Library 0.12.1](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-Icons-Library-0.12.1.sketch)

**Comment by reddolan** [comment]
Updates are complete. Here are links to the files:
[UI Library 0.12.2](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-0.12.2.sketch)
[UI Library - dark 0.12.2](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-dark-0.12.2.sketch)
[Icon Library 0.12.2](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-Icons-Library-0.12.12sketch)

**Comment by hippee-lee** [comment]
Sketch has been updated on the website for `0.12.2`
