### ISSUE TITLE
ESLint plugin for Clarity Core Adoption

### ISSUE THREAD

**Issue by sis0k0** [vmware/clarity#5528]
## Summary

The `@clr/eslint-plugin-clarity-adoption` package is an ESLint plugin aiming to ease the adoption of Clarity Core. The plugin provides different rules that detect and warn against the usage of Clarity Angular components. The selection of rules can vary based on the project configuration. For example, you can start with a single rule detecting only `clr-alert`s and gradually, add more restrictions.

## Note on fixers

Some of the components are suitable for automated replacement. Their ESLint rules can be augmented with a fixer that performs the replacement. For example, the `no-clr-icon` rule fixer replaces `<clr-icon dir="left"></clr-icon>` with `<cds-icon direction="left"></cds-icon>`.

## Rules

Please add your name next to a component if you've started working on its rule.

### Component detection

- [X] Alert - [`no-clr-alert`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-alert.md)
- [X] Button - [`no-clr-button`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-button.md)
- [X] Icon - [`no-clr-icon`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-icon.md)
- [X] Badge - [`no-clr-badge`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-badge.md)
- [X] Accordion - [`no-clr-accordion`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-accordion.md)
- [X] Checkbox - [`no-clr-checkbox`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-checkbox.md)
- [X] Datalist - [`no-clr-datalist`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-datalist.md)
- [X] Form - [`no-clr-form`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-form.md)
- [X] Input - [`no-clr-input`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-input.md)
- [X] List - [`no-clr-list`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-list.md)
- [X] Modal - [`no-clr-modal`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-modal.md)
- [X] Password - [`no-clr-password`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-password.md)
- [X] Radio - [`no-clr-radio`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-radio.md)
- [X] Range - [`no-clr-range`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-range.md)
- [X] Select - [`no-clr-select`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-select.md)
- [X] Textarea - [`no-clr-textarea`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-textarea.md)
- [X] Toggle - [`no-clr-toggle`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-toggle.md)

### Component replacement (fixer)

- [X] Icon - [`no-clr-icon`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-icon.md)
- [X] List - [`no-clr-list`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-list.md)
- [X] Badge - [`no-clr-badge`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-list.md)
- [x] Tag/Label - [`no-clr-label`](https://github.com/vmware/clarity/blob/next/packages/eslint-plugin-clarity-adoption/docs/rules/no-clr-label.md)
- [X] ~~Input~~ - Based on my POC only the most basic cases can be migrated with automated tooling.

### Adoption guide

- [ ] Add appropriate links to content in the adoption guide in the ESLint error messages once the adoption guide is published.

**Comment by bdryanovski** [comment]
Is this ready to be close?:)

**Comment by sis0k0** [comment]
The only item that's left is:
```
Add appropriate links to content in the adoption guide in the ESLint error messages once the adoption guide is published.
```

But I guess that could be done afterward.
